redditclone/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('user/<username>', views.user, name='user'),
]

redditclone/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:pk>/upvote', views.upvote, name='upvote'),
    path('<int:pk>/downvote', views.downvote, name='downvote'),
]

redditclone/redditclone/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', views.home, name='home'),
]

redditclone/accounts/models.py
from django.db import models

# Create your models here.
# class Profile(models.Model):  
#     user = models.OneToOneField(User, models.CASCADE)
    

redditclone/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, models.CASCADE)
    votes_total = models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %d %Y')

redditclone/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from posts.models import Post
from . import models
import logging

def user(request, username):
    try:
        logger = logging.getLogger(__name__)
        user_to_use = User.objects.get(username=username)
        logger.error('USERNAME: ' + user_to_use.username)
        logger.error('ID: ' + str(user_to_use.id))

        posts = Post.objects.filter(author=user_to_use.id).order_by('-votes_total')

        return render(request, 'accounts/user.html', {'user':user_to_use,'posts':posts})
    except User.DoesNotExist:
        return render(request, 'accounts/user.html', {"error":"User " + username + " does not exist."})

def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {"error":"Username has already been taken."})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {"error":"Passwords didn't match."})
        
    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            # Invalid
            return render(request, 'accounts/login.html', {"error":"The username and password didn't match."})
    else:
        return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

redditclone/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from . import models

# Create your views here.

@login_required
def create(request):
    if request.method == 'POST':
        # POST
        if request.POST['title'] and request.POST['url']:
            post_title = request.POST['title']
            post_url = request.POST['url']

            # Create new post object
            post = models.Post()
            post.title = post_title
            # Check url for http and https
            if post_url.startswith('http://') or post_url.startswith('https://'):
                post.url = post_url
            else:
                post_url = 'http://' + post_url
            post.url = post_url            
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error':'ERROR: You must include a title and a URL to create a post.'})
    else:
        # GET
        return render(request, 'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts':posts})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')

redditclone/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Login</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    {% if request.GET.next %}
    <input type="hidden" name="next" value={{request.GET.next}}
    {% endif %}
    Username
    <br />
    <input type="text" name="username" />
    <br />
    Password
    <br />
    <input type="password", name="password" />
    <br />
    <br />
    <input type="submit" class="btn btn-primary" value="Login" />
</form>

{% endblock %}

redditclone/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Sign Up!</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    Username
    <br />
    <input type="text" name="username" />
    <br />
    Password
    <br />
    <input type="password", name="password1" />
    <br />
    Confirm Password
    <br />
    <input type="password", name="password2" />
    <br />
    <br />
    <input type="submit" class="btn btn-primary" value="Sign Up!" />
</form>

{% endblock %}

redditclone/accounts/templates/accounts/user.html
{% extends 'base.html' %} {% block content %} {% if error %} <h3>{{ error }}</h3>
<br />
<br /> {% else %}


<h1>Posts by user {{ user.username }}</h1>

<br />
<br /> {% for post in posts.all %}

<table class="table-responsive">
    <tr>
        <td style="padding-right: 20px;">
            <a href="#" onclick="document.getElementById('frmUpvote{{ post.id }}').submit()">
                <i class="fas fa-caret-up"></i>
            </a>
            <br/> {{ post.votes_total }}
            <br/>
            <a href="#" onclick="document.getElementById('frmDownvote{{ post.id }}').submit()">
                <i class="fas fa-caret-down"></i>
            </a>
        </td>
        <td>
            <a href={{post.url}}>{{ post.title }}</a>
            <br /> {{post.pub_date_pretty}} by {{post.author.username}}
        </td>
    </tr>
</table>

<form method="POST" id="frmDownvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}">
    {% csrf_token %}
    <input type="hidden" value="Down" />
</form>
<form method="POST" id="frmUpvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}">
    {% csrf_token %}
    <input type="hidden" value="Up" />
</form>
<br /> {% endfor %} {% endif %}{% endblock %}

redditclone/posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<h1>New Post</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}

    Title:
    <br />
    <input type="text" name="title" />
    <br />
    URL:
    <br />
    <input type="text", name="url" />
    <br />
    <br />
    <input type="submit" class="btn btn-primary" value="Post" />
</form>

{% endblock %}

redditclone/posts/templates/posts/home.html
{% extends 'base.html' %} {% block content %}

<h1>The Homepage of Nowhere</h1>
<a href="{% url 'posts:create' %}" class="btn btn-primary">New Post</a>

<br />
<br /> {% for post in posts.all %}

<table class="table-responsive">
    <tr>
        <td style="padding-right: 20px;">
            <a href="#" onclick="document.getElementById('frmUpvote{{ post.id }}').submit()">
                <i class="fas fa-caret-up"></i>
            </a>
            <br/> {{ post.votes_total }}
            <br/>
            <a href="#" onclick="document.getElementById('frmDownvote{{ post.id }}').submit()">
                <i class="fas fa-caret-down"></i>
            </a>
        </td>
        <td>
            <a href={{post.url}}>{{ post.title }}</a>
            <br /> {{post.pub_date_pretty}} by <a href="{% url 'accounts:user' post.author.username %}">{{post.author.username}}</a>
        </td>
    </tr>
</table>

<form method="POST" id="frmDownvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}">
    {% csrf_token %}
    <input type="hidden" value="Down" />
</form>
<form method="POST" id="frmUpvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}">
    {% csrf_token %}
    <input type="hidden" value="Up" />
</form>
<br /> {% endfor %} {% endblock %}

redditclone/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">

    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl"
        crossorigin="anonymous"></script>

    <title>Reddit Clone</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="document.getElementById('logout').submit()">Logout</a>
                </li>
                <form id="logout" method="POST", action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <input type="hidden" />
                </form>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>